biped:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  hip_RF_controller:
    type: effort_controllers/JointPositionController
    joint: hip_RF
    pid: {p: 100.0, i: 0.01, d: 10.0}

  hip_RB_controller:
    type: effort_controllers/JointPositionController
    joint: hip_RB
    pid: {p: 100.0, i: 0.01, d: 10.0}

  hip_LF_controller:
    type: effort_controllers/JointPositionController
    joint: hip_LF
    pid: {p: 100.0, i: 0.01, d: 10.0}

  hip_LB_controller:
    type: effort_controllers/JointPositionController
    joint: hip_LB
    pid: {p: 100.0, i: 0.01, d: 10.0}

  knee_RF_controller:
    type: effort_controllers/JointPositionController
    joint: knee_RF
    pid: {p: 100.0, i: 0.01, d: 10.0}

  knee_RB_controller:
    type: effort_controllers/JointPositionController
    joint: knee_RB
    pid: {p: 100.0, i: 0.01, d: 10.0}

  knee_LF_controller:
    type: effort_controllers/JointPositionController
    joint: knee_LF
    pid: {p: 100.0, i: 0.01, d: 10.0}

  knee_LB_controller:
    type: effort_controllers/JointPositionController
    joint: knee_LB
    pid: {p: 100.0, i: 0.01, d: 10.0}
