# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link1
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: dxel1__link2
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link3
  pid: {p: 20000.0, i: 50, d: 1000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: dxel2__link4
  pid: {p: 2000.0, i: 50, d: 200.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link5
  pid: {p: 700.0, i: 50, d: 70.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: dxel3__link6
  pid: {p: 2000.0, i: 100, d: 500.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link7
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: dxel4__link8
  pid: {p: 20000.0, i: 50, d: 1000.0}

