// Generated by gencpp from file quadped1/JointArduino.msg
// DO NOT EDIT!


#ifndef QUADPED1_MESSAGE_JOINTARDUINO_H
#define QUADPED1_MESSAGE_JOINTARDUINO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace quadped1
{
template <class ContainerAllocator>
struct JointArduino_
{
  typedef JointArduino_<ContainerAllocator> Type;

  JointArduino_()
    : header()
    , joint1()
    , joint2()  {
    }
  JointArduino_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint1(_alloc)
    , joint2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _joint1_type;
  _joint1_type joint1;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _joint2_type;
  _joint2_type joint2;





  typedef boost::shared_ptr< ::quadped1::JointArduino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadped1::JointArduino_<ContainerAllocator> const> ConstPtr;

}; // struct JointArduino_

typedef ::quadped1::JointArduino_<std::allocator<void> > JointArduino;

typedef boost::shared_ptr< ::quadped1::JointArduino > JointArduinoPtr;
typedef boost::shared_ptr< ::quadped1::JointArduino const> JointArduinoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadped1::JointArduino_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadped1::JointArduino_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace quadped1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'quadped1': ['/home/akshatha_kamath/catkin_ws/src/quadped1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::quadped1::JointArduino_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadped1::JointArduino_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadped1::JointArduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadped1::JointArduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadped1::JointArduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadped1::JointArduino_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadped1::JointArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8817d807068ab53aa400c3c794b32ee1";
  }

  static const char* value(const ::quadped1::JointArduino_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8817d807068ab53aULL;
  static const uint64_t static_value2 = 0xa400c3c794b32ee1ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadped1::JointArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadped1/JointArduino";
  }

  static const char* value(const ::quadped1::JointArduino_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadped1::JointArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
std_msgs/Float64 joint1\n\
std_msgs/Float64 joint2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::quadped1::JointArduino_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadped1::JointArduino_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint1);
      stream.next(m.joint2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointArduino_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadped1::JointArduino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadped1::JointArduino_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint1: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.joint2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADPED1_MESSAGE_JOINTARDUINO_H
