// Generated by gencpp from file quadped1/jointstatesRequest.msg
// DO NOT EDIT!


#ifndef QUADPED1_MESSAGE_JOINTSTATESREQUEST_H
#define QUADPED1_MESSAGE_JOINTSTATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadped1
{
template <class ContainerAllocator>
struct jointstatesRequest_
{
  typedef jointstatesRequest_<ContainerAllocator> Type;

  jointstatesRequest_()
    : name()  {
    }
  jointstatesRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::quadped1::jointstatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadped1::jointstatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct jointstatesRequest_

typedef ::quadped1::jointstatesRequest_<std::allocator<void> > jointstatesRequest;

typedef boost::shared_ptr< ::quadped1::jointstatesRequest > jointstatesRequestPtr;
typedef boost::shared_ptr< ::quadped1::jointstatesRequest const> jointstatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadped1::jointstatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadped1::jointstatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace quadped1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'quadped1': ['/home/akshatha_kamath/catkin_ws/src/quadped1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::quadped1::jointstatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadped1::jointstatesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadped1::jointstatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadped1::jointstatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadped1::jointstatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadped1::jointstatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadped1::jointstatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f2d21c30868b92dc41a0431bacd47b2";
  }

  static const char* value(const ::quadped1::jointstatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f2d21c30868b92dULL;
  static const uint64_t static_value2 = 0xc41a0431bacd47b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadped1::jointstatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadped1/jointstatesRequest";
  }

  static const char* value(const ::quadped1::jointstatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadped1::jointstatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n\
";
  }

  static const char* value(const ::quadped1::jointstatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadped1::jointstatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointstatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadped1::jointstatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadped1::jointstatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADPED1_MESSAGE_JOINTSTATESREQUEST_H
